# Generated by Django 4.1.6 on 2023-02-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_evento', models.CharField(max_length=30, null=True)),
                ('tipo_de_evento', models.CharField(max_length=30, null=True)),
                ('desc', models.TextField()),
                ('fecha', models.DateField()),
                ('est', models.CharField(default='Pendiente por Revisar', max_length=22)),
                ('gestion', models.CharField(default='Pendiente por Revisar', max_length=22)),
            ],
        ),
    ]
